# The Docker image to run your workspace in.
image:
  file: .gitpod.dockerfile

# Commands on:
tasks:
  # install kafka
  - init: >
      wget https://ftp.heanet.ie/mirrors/www.apache.org/dist/kafka/2.6.0/kafka_2.13-2.6.0.tgz && 
      tar -xvf kafka_2.13-2.6.0.tgz && 
      rm kafka_2.13-2.6.0.tgz
  # setup workspace
    command: > 
      cd kafka_2.13-2.6.0/ &&
      mkdir -p tmp/zookeeper/ &&
      mkdir -p tmp/kafka-logs/ &&
      echo 'export PATH="$PATH:$GITPOD_REPO_ROOT/kafka_2.13-2.6.0/bin"' >> ~/.bashrc &&
      echo 'alias zk="sh zookeeper-server-start.sh config/zookeeper.properties"' >> ~/.bashrc &&
      echo 'alias kk="sh kafka-server-start.sh config/server.properties"' >> ~/.bashrc &&
      source ~/.bashrc

# Ports to expose
ports:
  - port: 8080
  - port: 2181
  - port: 9092

# Install vscode extensions
vscode:
  extensions:
    - formulahendry.auto-close-tag@0.5.6:oZ/8R2VhZEhkHsoeO57hSw==
    - mkaufman.HTMLHint@0.6.0:TdNYbCmjW8N3yiaPW4/adg==
    - ms-python.python@2019.8.30787:TnGEOx35GXMhyKLjDGz9Aw==
